-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) TOTAL_SALES
FROM BOOK_SALES BS
    LEFT JOIN BOOK B
    ON BS.BOOK_ID=B.BOOK_ID
    LEFT JOIN AUTHOR A
    ON B.AUTHOR_ID=A.AUTHOR_ID
WHERE B.BOOK_ID IS NOT NULL
    AND A.AUTHOR_ID IS NOT NULL
    AND DATE_FORMAT(BS.SALES_DATE, '%Y-%m')='2022-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC