-- 코드를 작성해주세요
SELECT DISTINCT ED_G3.ID
FROM ECOLI_DATA ED_G3
    LEFT JOIN ECOLI_DATA ED_G2
    ON ED_G3.PARENT_ID = ED_G2.ID
    LEFT JOIN ECOLI_DATA ED_G1
    ON ED_G2.PARENT_ID = ED_G1.ID
    LEFT JOIN ECOLI_DATA ED_G0
    ON ED_G1.PARENT_ID = ED_G0.ID
WHERE ED_G2.ID IS NOT NULL
    AND ED_G1.ID IS NOT NULL
    AND ED_G0.ID IS NULL
ORDER BY ED_G3.ID