-- 코드를 작성해주세요
WITH PERCENT AS(
    SELECT ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) SIZE_GROUP
    FROM ECOLI_DATA 
),
COLONY_NAME_LIST AS(
    SELECT ID,
        CASE
            WHEN PERCENT.SIZE_GROUP = 1 THEN 'CRITICAL'
            WHEN PERCENT.SIZE_GROUP = 2 THEN 'HIGH'
            WHEN PERCENT.SIZE_GROUP = 3 THEN 'MEDIUM'
            WHEN PERCENT.SIZE_GROUP = 4 THEN 'LOW'
        END COLONY_NAME
    FROM PERCENT
)

SELECT ED.ID, CNL.COLONY_NAME
FROM ECOLI_DATA ED
    INNER JOIN COLONY_NAME_LIST CNL
    ON ED.ID = CNL.ID
ORDER BY ED.ID