-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, 
    CONCAT(UGU.CITY, ' ', UGU.STREET_ADDRESS1, ' ', UGU.STREET_ADDRESS2) 전체주소, 
    CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) 전화번호
FROM USED_GOODS_USER UGU
WHERE USER_ID IN (
    SELECT USER_ID
    FROM USED_GOODS_USER UGU
        JOIN USED_GOODS_BOARD UGB
        ON UGU.USER_ID=UGB.WRITER_ID
    GROUP BY UGU.USER_ID
    HAVING COUNT(*)>=3
)
ORDER BY USER_ID DESC