-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, 
    ROUND(AVG(IF(RR.REVIEW_SCORE IS NULL, 0, RR.REVIEW_SCORE)), 2) SCORE
FROM REST_INFO RI
    LEFT JOIN REST_REVIEW RR
    ON RI.REST_ID = RR.REST_ID
WHERE RR.REST_ID IS NOT NULL
    AND RI.ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC

# SELECT RI.REST_ID, RI.REST_NAME, RI.ADDRESS, RR.REVIEW_ID,
#     ROUND(AVG(IF(RR.REVIEW_SCORE IS NULL, 0, RR.REVIEW_SCORE)), 2) SCORE
# FROM REST_INFO RI
#     LEFT JOIN REST_REVIEW RR
#     ON RI.REST_ID = RR.REST_ID
# GROUP BY RI.REST_ID