-- 코드를 입력하세요
# SELECT CAR_ID, 
#     IF(CAR_ID IN (
#             SELECT DISTINCT CAR_ID
#             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#             WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-10-16'
#                 AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-10-16'
#         ), 
#        '대여중', '대여 가능') AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# ORDER BY CAR_ID DESC

(SELECT CAR_ID, '대여중' AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-10-16'
        AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-10-16'
)
UNION
SELECT CAR_ID, '대여 가능' AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID NOT IN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m-%d') <= '2022-10-16'
        AND DATE_FORMAT(END_DATE, '%Y-%m-%d') >= '2022-10-16'
))
ORDER BY CAR_ID DESC