-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT FP
    JOIN FOOD_ORDER FO
    ON FP.PRODUCT_ID=FO.PRODUCT_ID
WHERE FO.PRODUCT_ID IS NOT NULL
    AND DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID