-- 코드를 입력하세요
WITH VALUE AS (
    SELECT HISTORY.HISTORY_ID, 
        (DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1) PERIOD,
        CAR.CAR_TYPE,
        CAR.DAILY_FEE,
        CASE 
            WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END PERIOD_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
        LEFT JOIN CAR_RENTAL_COMPANY_CAR CAR
        ON HISTORY.CAR_ID = CAR.CAR_ID
    WHERE CAR.CAR_TYPE = '트럭'
)

SELECT VALUE.HISTORY_ID,
    ROUND((VALUE.PERIOD * (100 - IFNULL(PLAN.DISCOUNT_RATE, 0)) * VALUE.DAILY_FEE / 100)) FEE
FROM VALUE
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN 
    ON VALUE.CAR_TYPE = PLAN.CAR_TYPE
        AND VALUE.PERIOD_TYPE = PLAN.DURATION_TYPE
ORDER BY FEE DESC, VALUE.HISTORY_ID DESC