-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM (
        SELECT FLAVOR, SUM(TOTAL_ORDER) FH_SUM
        FROM FIRST_HALF 
        GROUP BY FLAVOR
    ) FH
    LEFT JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) J_SUM
        FROM JULY 
        GROUP BY FLAVOR
    ) J
    ON FH.FLAVOR=J.FLAVOR
ORDER BY (FH.FH_SUM + J.J_SUM) DESC
LIMIT 3