-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(UGB.PRICE) TOTAL_SALES
FROM USED_GOODS_USER USU
    LEFT JOIN USED_GOODS_BOARD UGB
    ON USU.USER_ID=UGB.WRITER_ID
WHERE WRITER_ID IS NOT NULL
    AND STATUS='DONE'
GROUP BY USER_ID
HAVING total_sales >= 700000
ORDER BY TOTAL_SALES