-- 코드를 작성해주세요
SELECT HG.EMP_NO, HE.EMP_NAME, 
    CASE
        WHEN AVG(HG.SCORE) >= 96
            THEN 'S'
        WHEN AVG(HG.SCORE) >= 90
            THEN 'A'
        WHEN AVG(HG.SCORE) >= 80
            THEN 'B'
        ELSE 'C'
    END GRADE,
    CASE
        WHEN AVG(HG.SCORE) >= 96
            THEN HE.SAL * 0.2
        WHEN AVG(HG.SCORE) >= 90
            THEN HE.SAL * 0.15
        WHEN AVG(HG.SCORE) >= 80
            THEN HE.SAL * 0.10
        ELSE 0
    END BONUS
FROM HR_GRADE HG
    LEFT JOIN HR_EMPLOYEES HE
    ON HG.EMP_NO = HE.EMP_NO
    LEFT JOIN HR_DEPARTMENT HD
    ON HE.DEPT_ID = HD.DEPT_ID
WHERE HE.EMP_NO IS NOT NULL
    AND HD.DEPT_ID IS NOT NULL
GROUP BY HG.EMP_NO
ORDER BY HG.EMP_NO