-- 코드를 입력하세요
SELECT MP1.MEMBER_NAME, RR1.REVIEW_TEXT, DATE_FORMAT(RR1.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW RR1
    JOIN MEMBER_PROFILE MP1
    ON RR1.MEMBER_ID=MP1.MEMBER_ID
WHERE RR1.MEMBER_ID = (
    SELECT MOST_REVIEWR.MOST_REVIEW_ID
    FROM (
        SELECT RR2.MEMBER_ID MOST_REVIEW_ID, COUNT(*) CNT
        FROM REST_REVIEW RR2
            JOIN MEMBER_PROFILE MP2
            ON RR2.MEMBER_ID=MP2.MEMBER_ID
        GROUP BY RR2.MEMBER_ID
        ORDER BY CNT DESC
    ) MOST_REVIEWR
    LIMIT 1
)
ORDER BY REVIEW_DATE, RR1.REVIEW_TEXT