-- 코드를 입력하세요
SELECT DISTINCT CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
    ON CRCC.CAR_ID=CRCRH.CAR_ID
WHERE CRCRH.START_DATE IS NOT NULL
    AND MONTH(CRCRH.START_DATE)=10
    AND CAR_TYPE='세단'
ORDER BY CRCC.CAR_ID DESC