-- 코드를 작성해주세요
SELECT FI1.ID, FNI.FISH_NAME, FI1.LENGTH
FROM FISH_INFO FI1
    LEFT JOIN FISH_NAME_INFO FNI
    ON FI1.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI1.FISH_TYPE, FI1.LENGTH) IN (
    SELECT FI2.FISH_TYPE, MAX(FI2.LENGTH) MAX_LEN
    FROM FISH_INFO  FI2
    GROUP BY FI2.FISH_TYPE
)
ORDER BY FI1.ID