# -- 코드를 입력하세요
# SELECT UGB.TITLE, UGR.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, date_format(UGR.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
# FROM USED_GOODS_REPLY UGR
#     LEFT JOIN USED_GOODS_BOARD UGB
#     ON UGR.BOARD_ID=UGB.BOARD_ID
# WHERE 
#     YEAR(UGR.CREATED_DATE)=2022
#     AND MONTH(UGR.CREATED_DATE)=10
# ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC

SELECT TITLE, BOARD.BOARD_ID, REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS REPLY
    LEFT JOIN USED_GOODS_BOARD AS BOARD
    ON REPLY.BOARD_ID=BOARD.BOARD_ID
WHERE DATE_FORMAT(BOARD.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY REPLY.CREATED_DATE, TITLE