-- 코드를 작성해주세요
SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, ROUND(AVG(IF(HE.SAL IS NULL, 0, HE.SAL)), 0) AVG_SAL
FROM HR_DEPARTMENT HD
    LEFT JOIN HR_EMPLOYEES HE
    ON HD.DEPT_ID = HE.DEPT_ID
WHERE HE.DEPT_ID IS NOT NULL
GROUP BY HD.DEPT_ID
ORDER BY AVG_SAL DESC