-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE UGF
WHERE BOARD_ID IN (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD UGB1
    WHERE UGB1.VIEWS IN (
        SELECT MAX(UGB2.VIEWS)
        FROM USED_GOODS_BOARD UGB2
    )
)
ORDER BY UGF.FILE_ID DESC