-- 코드를 작성해주세요
SELECT COUNT(*) FISH_COUNT, 
    MAX(FI.LENGTH) MAX_LENGTH, 
    FI.FISH_TYPE
FROM (
        SELECT FISH_TYPE, 
            AVG(IF(LENGTH IS NULL OR LENGTH <= 10, 10, LENGTH)) AVG_LENGTH
        FROM FISH_INFO 
        GROUP BY FISH_TYPE
    ) AS FISH_INFO_AVG
    LEFT JOIN FISH_INFO FI
    ON FISH_INFO_AVG.FISH_TYPE = FI.FISH_TYPE
WHERE FISH_INFO_AVG.AVG_LENGTH >= 33
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE